### ISSUE TITLE
Implement hash functions

### ISSUE THREAD

**Issue by radka-j** [alan-turing-institute/repro-catalogue#11]
Subtask of #6 

Existing hash functions (in `catalogue.py`):
- `hash_file`
- `hash_dir_by_file`
- `hash_dir_full`
- `store_hash`
- `load_hash`

Functions that are used but not yet implemented:
- [x] `get_h`
- [x] `hash_input`
- [x] `hash_output`
- [x] `hash_code`

Most of these should just call the existing functions.

**Comment by Islast** [comment]
Hey @radka 
*  `get_h` is implemented within the `check_hashes` function as
   `get_h = lambda x: x.values()[0]`
* `hash_input`, `hash_output` and `hash_code` should, as you say, call the other functions. I put off implementing these in particular because they involve decisions about how these data types ought to be hashed (e.g. hash_file or hash_dir) - I was considering making these configurable via some config file.

**Comment by radka-j** [comment]
@Islast Thanks! I missed that.

**Comment by radka-j** [comment]
@edaub we need to finalise what the final output should look like. Or should we make this configurable as suggested by @Islast? 

The initial proposal is to:
- hash the directory of the input data
- hash the directory with the analysis code + store the git commit hash
- hash the analysis outputs by file 

The final output has the path to the directory/file and the related hash.

I don't have a strong preference either way at the moment.
