### ISSUE TITLE
compare_hashes should return directory paths

### ISSUE THREAD

**Issue by radka-j** [alan-turing-institute/repro-catalogue#35]
The `compare_hashes` function compares hashes and returns which match, differ or cannot be compared: 
- for `output_data`, the function returns the file paths.
- for `timestamp`, `input_data` and `code`, the function returns these arg names.

For example, it might return:
```
results differ in 1 places:
===========================
timestamp
input_data
results match in 1 places:
==========================
code
results could not be compared in 1 places:
==========================================
results/20200422-154401.csv
```

I think that for `input_data` and `code`, we should also print the paths that were actually compared for improved transparency.

@edaub what do you think?

**Comment by radka-j** [comment]
Although this would cause issues if I rerun your code and want to compare whether I have the same results but I might have a different directory structure. So maybe the current behaviour is correct.

**Comment by edaub** [comment]
I think it should be fine to include the specific paths rather than the generic input/code designation. The hashes are based on the data in the underlying files, not the path, so the comparisons are still valid regardless of how you choose to display the results.

The relative directory structure within the input data directory needs to be the same in order to obtain the same hashes (or at least the individual file hashes have to be added to the hash function in the same order) for the comparison to work. So again, I don't think it matters which you choose, so if you think the path is more informative then we should do that.

**Comment by radka-j** [comment]
Lets go with that then, thanks.

**Comment by radka-j** [comment]
Having thought about it, I think it's fine to leave it as is.
